### ISSUE TITLE
Retrying setup: 'lines' Exception: Could not get 6 month token: You need to sign in first

### ISSUE THREAD

**Issue by vertIcod3r** [posixx/home_assistant_custom_envoy#1]
Hi @posixx 
Getting the errors listed in the title. 
Debug logs:

raceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/enphase_envoy/__init__.py", line 82, in async_update_data
    data[description.key] = await getattr(
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 558, in production_l1
    production_l1 = raw_json["production"][idx]["lines"][0]["wNow"]
KeyError: 'lines'
2023-01-09 14:28:28.299 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Envoy 122234000xxx' for enphase_envoy integration not ready yet: 'lines'; Retrying in background
2023-01-09 14:28:35.124 ERROR (MainThread) [custom_components.enphase_envoy] Unexpected error fetching envoy Envoy 122234000xxx data: Could not get 6 month token: You need to sign in first
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/enphase_envoy/__init__.py", line 50, in async_update_data
    await envoy_reader.getData()
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 379, in getData
    await self._getEnphaseToken()
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 272, in _getEnphaseToken
    token_json = await self._fetch_owner_token_json()
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 260, in _fetch_owner_token_json
    raise Exception("Could not get 6 month token: " + msg)
Exception: Could not get 6 month token: You need to sign in first
2023-01-09 14:28:53.889 ERROR (MainThread) [custom_components.enphase_envoy] Unexpected error fetching envoy Envoy 122234000xxx data: 'lines'

**Comment by posixx** [comment]
Unfortunately i cannot help you at this moment as my envoy is still on D5 so no token needed. I'm not able to debug. Are you sure you setup the integration correctly? Authentication is not changed from plugin from @briancmpbll so it should work..

**Comment by RoadXY** [comment]
I have installed this plugin succesfully on both a firmware v5 and v7 (of a friend of mine).

It could be something to do with the sign in since the log shows: 
_Unexpected error fetching envoy Envoy 122234000xxx data: Could not get 6 month token: You need to sign in first_

**Comment by vertIcod3r** [comment]
Okay, went to check it again just now. So a day later. And it is working now without changing anything on the HA side. So lets just close it and wait and see.
