### ISSUE TITLE
Envoy Metered S without CT - Error: KeyError: 'lines'

### ISSUE THREAD

**Issue by SanderH** [posixx/home_assistant_custom_envoy#12]
Having a new Enphase system with Envoy Metered S without CT monitoring (we expected 6 of them, but installer never heard of those things...).

The monitoring within HA gives the following error:
`Unexpected error fetching envoy Envoy ********* data: 'lines'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
return await self.update_method()
File "/config/custom_components/enphase_envoy/__init__.py", line 82, in async_update_data
data[description.key] = await getattr(
File "/config/custom_components/enphase_envoy/envoy_reader.py", line 558, in production_l1
production_l1 = raw_json["production"][idx]["lines"][0]["wNow"]
KeyError: 'lines'`

Looking at the logs in HA, the data is:
`{
    "production": [
        {
            "type": "inverters",
            "activeCount": 8,
            "readingTime": 1682446988,
            "wNow": 187,
            "whLifetime": 65255
        },
        {
            "type": "eim",
            "activeCount": 0,
            "measurementType": "production",
            "readingTime": 1682446991,
            "wNow": 0.704,
            "whLifetime": 0.0,
            "varhLeadLifetime": 0.0,
            "varhLagLifetime": 0.0,
            "vahLifetime": 0.0,
            "rmsCurrent": 0.223,
            "rmsVoltage": 689.206,
            "reactPwr": 0.0,
            "apprntPwr": 51.373,
            "pwrFactor": 0.0,
            "whToday": 0.0,
            "whLastSevenDays": 0.0,
            "vahToday": 0.0,
            "varhLeadToday": 0.0,
            "varhLagToday": 0.0,
            "lines": [
                {
                    "wNow": 0.704,
                    "whLifetime": 0.0,
                    "varhLeadLifetime": 0.0,
                    "varhLagLifetime": 0.0,
                    "vahLifetime": 0.0,
                    "rmsCurrent": 0.098,
                    "rmsVoltage": 228.003,
                    "reactPwr": 0.0,
                    "apprntPwr": 22.518,
                    "pwrFactor": 0.0,
                    "whToday": 0.0,
                    "whLastSevenDays": 0.0,
                    "vahToday": 0.0,
                    "varhLeadToday": 0.0,
                    "varhLagToday": 0.0
                },
...`

I guess it's going wrong in the code on lines 557, 569 and 581 `(idx = 1 if self.isMeteringEnabled else 0)` ending up with 0 as there is no metering, but it's still the 2nd set of data in the json containing the data, not the first as you seem to be expecting. Looks like it should always be 1 instead of 0.

Also without the CT's, there is still data for wNow, so why not show it?

At least now it's breaking without even attempting to show the inverter data
`[
  {
    "serialNumber": "******",
    "lastReportDate": 1682430151,
    "devType": 1,
    "lastReportWatts": 179,
    "maxReportWatts": 298
  },
  {
    "serialNumber": "******",
    "lastReportDate": 1682430152,
    "devType": 1,
    "lastReportWatts": 177,
    "maxReportWatts": 297
  },
...`
, which is containing good data which is now not showing because of this error.

**Comment by rmjjanssen1** [comment]
Hi,

@SanderH have you selected 3 phase support during integration setup/configuration? I have the same error and I suspect that although I have installed my production CTs (and enabled 3phase support during config), the integration is trying to fetch the CT metering but they are not reported as they are NOT yet enabled on the ENVOY. I found out that after installation of the CTs you need to enable the metered options in your Envoy. You can check this by logging into the Web interface of your Envoy under https://xxx.xxx.xxx.xxx/home (Use your Enlighten online credentials to login)

@posixx would it be an idea that the integration checks if metering is enabled (using https://xxx.xxx.xxx.xxx/ivp/meters) when 3phase support is selected during configuration. If not enabled the integration setup does not end in error, but it is setup with only supported data returned, with a log entry that CTs must be installed and metering must be enabled in Envoy!?

**Comment by SanderH** [comment]
Even een update. Had inmiddels een fork gemaakt en een paar regels aangepast waardoor het werkte.

En een week later (na enig aandringen) alsnog de CT's gekregen van de installateur. Na deze zelf geinstalleerd te hebben in de groepenkast heeft HA deze inmiddels ook opgepikt en draait de boel nu zoals eigenlijk al had moeten zijn.
