### ISSUE TITLE
3phase related error

### ISSUE THREAD

**Issue by rmjjanssen1** [posixx/home_assistant_custom_envoy#15]
Hi last week the production CTs were enabled and re-installed this integration with 3ph checked/enabled. Getting the below error. Any suggestion to get this fixed?

2023-05-14 14:08:46.855 ERROR (MainThread) [custom_components.enphase_envoy] Unexpected error fetching envoy Envoy *******data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 217, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/enphase_envoy/__init__.py", line 82, in async_update_data
    data[description.key] = await getattr(
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 629, in consumption_l2
    consumption_l2 = raw_json["consumption"][0]["lines"][1]["wNow"]
IndexError: list index out of range

**Comment by JoryHogeveen** [comment]
Same issue here, also with 3 phase system.

**Comment by JoryHogeveen** [comment]
Found the problem.
I didn't install consumption meters and when setting this addon to 3 phase it requires both production and consumption to be enabled and set to 3 phases.

Might be best if the module checks for data availability instead of a fixed reliance on a specific configtation.

**Comment by JoryHogeveen** [comment]
I just added the consumption meters in enlighten without connecting any CT's. It isn't the most pretty solution but it works :)

**Comment by JoryHogeveen** [comment]
Yes I installed it myself. You will need to access the system in order to change this.
You could try to access it locally (IP) and login but I'm not sure if that works if you do not have an installer account.
