### ISSUE TITLE
Envoy-S D7 firmware. does not connect without a password?

### ISSUE THREAD

**Issue by RacerBas** [posixx/home_assistant_custom_envoy#2]
The integration finds the envoy and it's serial number but I cannot add it to home assistant, it keeps saying failed to connect?

**Comment by RoadXY** [comment]
Yes you have to login to your Enphase account to get a valid token because Enphase enhanced the local API security.
You can read more here:
https://support.enphase.com/s/article/IQ-Gateway-Software-7-0-86-Release-Notes

**Comment by RacerBas** [comment]
Does that work with this plugin or do I need something else?

**Comment by RoadXY** [comment]
This plugin is compatibel with both version 5 and 7 of the firmware

**Comment by RacerBas** [comment]
I connected it to my enphase account using Option B in the documentation but in HASS I get an unexpected error trying to connect:

`Logger: custom_components.enphase_envoy.config_flow
Source: custom_components/enphase_envoy/envoy_reader.py:257
Integration: Enphase Envoy
First occurred: 12:51:25 (3 occurrences)
Last logged: 12:51:57

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/enphase_envoy/config_flow.py", line 162, in async_step_user
    envoy_reader = await validate_input(self.hass, user_input)
  File "/config/custom_components/enphase_envoy/config_flow.py", line 44, in validate_input
    await envoy_reader.getData()
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 379, in getData
    await self._getEnphaseToken()
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 272, in _getEnphaseToken
    token_json = await self._fetch_owner_token_json()
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 257, in _fetch_owner_token_json
    resp_json = resp.json()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by RacerBas** [comment]
figured it out, enphase didnt connect properly to DNS but after a reconnect I can authenticate the integration now.
