### ISSUE TITLE
Sensors regarding production are broken

### ISSUE THREAD

**Issue by bropie** [posixx/home_assistant_custom_envoy#24]
After a OTA update to Envoy version D7.6.175 the sensors regarding energy production and consumption stopped reporting values.

**Comment by rdvanbuuren** [comment]
Here I have the same issue after setting it up.

Here's the logs:
```
Logger: custom_components.enphase_envoy
Source: custom_components/enphase_envoy/envoy_reader.py:558
Integration: Enphase Envoy
First occurred: 7:32:34 PM (4 occurrences)
Last logged: 7:33:32 PM

Unexpected error fetching envoy Envoy 122140070010 data: 'lines'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enphase_envoy/__init__.py", line 82, in async_update_data
    data[description.key] = await getattr(
                            ^^^^^^^^^^^^^^
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 558, in production_l1
    production_l1 = raw_json["production"][idx]["lines"][0]["wNow"]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'lines'
```
