### ISSUE TITLE
Unexpected error: List index out of range

### ISSUE THREAD

**Issue by vertIcod3r** [posixx/home_assistant_custom_envoy#4]
Getting the following, on a 3 phase system. When I do not check the 3 phase system box it works. 

2023-02-06 20:54:02.099 ERROR (MainThread) [custom_components.enphase_envoy] Unexpected error fetching envoy Envoy xxxxxxxxxxx data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/enphase_envoy/__init__.py", line 82, in async_update_data
    data[description.key] = await getattr(
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 629, in consumption_l2
    consumption_l2 = raw_json["consumption"][0]["lines"][1]["wNow"]
IndexError: list index out of range

Could this be because consumption metering is not enabled?

![image](https://user-images.githubusercontent.com/50245719/217193329-a25e9f4f-b9aa-4ffa-b6cc-e894f1fb2951.png)

@posixx Any ideas?

**Comment by posixx** [comment]
This happens when you enable 3 phase system box on a 1 phase envoy installation. You sure you have a 3-phase system? What's the output of http://ip_of_your_envoy/production.json?details=1 ?

**Comment by vertIcod3r** [comment]
Yes it is a 3 phase system. Output from the production.json:

[production.json.zip](https://github.com/posixx/home_assistant_custom_envoy/files/10673327/production.json.zip)

**Comment by posixx** [comment]
There is only one consumption phase. Looks like a wrongly configured envoy setup; only one phase of your main power system is monitored for consumption. It should be 3.

**Comment by vertIcod3r** [comment]
@posixx Yes that seems to be the problem. Sorry for bothering you with this. Thanks for pointing me in the right direction.
